import { fromFileUrl, join, toFileUrl } from "@std/path";

const modulesDir = fromFileUrl(new URL("../src/modules", import.meta.url));
const manifestPath = join(modulesDir, "manifest.ts");

function toIdentifier(name: string): string {
  let id = name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  if (!id) id = "_";
  return id;
}

async function scanModules(): Promise<Map<string, string>> {
  const entries = new Map<string, string>();

  for await (const entry of Deno.readDir(modulesDir)) {
    const name = entry.name;
    if (name.startsWith(".")) continue;
    if (name === "manifest.ts") continue;

    if (entry.isFile) {
      if (!name.endsWith(".ts") && !name.endsWith(".tsx")) continue;
      entries.set(name.replace(/\.(ts|tsx)$/, ""), `./${name}`);
    } else if (entry.isDirectory) {
      for (const candidate of ["index.ts", "index.tsx"]) {
        try {
          const path = join(modulesDir, name, candidate);
          await Deno.stat(path);
          entries.set(name, `./${name}/${candidate}`);
          break;
        } catch {
          continue;
        }
      }
    }
  }

  return entries;
}

async function generateManifest(): Promise<void> {
  const entries = await scanModules();
  const lines: string[] = [];

  lines.push("// Auto-generated by tools/generate-manifest.ts — do not edit manually");
  lines.push("");

  const seen = new Set<string>();
  for (const [label, importPath] of entries) {
    let ident = toIdentifier(label);
    while (seen.has(ident)) {
      ident = `_${ident}`;
    }
    seen.add(ident);
    lines.push(`export { default as ${ident} } from "${importPath}";`);
  }

  if (lines.length > 2) lines.push("");

  await Deno.writeTextFile(manifestPath, lines.join("\n"));
  console.error(`Generated manifest with ${entries.size} module(s): ${[...entries.keys()].join(", ")}`);
}

if (import.meta.main) {
  await generateManifest();
}
