import { fromFileUrl, join } from "@std/path";

const modulesDir = fromFileUrl(new URL("../src/modules", import.meta.url));
const manifestPath = join(modulesDir, "manifest.ts");

function toIdentifier(name: string): string {
  let id = name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  if (!id) id = "_";
  return id;
}

function skipEntry(name: string): boolean {
  return name.startsWith(".") || name === "manifest.ts";
}

async function findIndexFile(dirPath: string): Promise<string | null> {
  for (const candidate of ["index.ts", "index.tsx"]) {
    try {
      const path = join(dirPath, candidate);
      const stat = await Deno.stat(path);
      if (stat.isFile) return path;
    } catch {
      continue;
    }
  }
  return null;
}

async function scanDirectory(
  dirPath: string,
  prefix: string,
  entries: Map<string, string>,
): Promise<void> {
  for await (const entry of Deno.readDir(dirPath)) {
    const name = entry.name;
    if (skipEntry(name)) continue;

    const fullPath = join(dirPath, name);
    const relPath = prefix ? `${prefix}/${name}` : name;

    if (entry.isFile) {
      if (!name.endsWith(".ts") && !name.endsWith(".tsx")) continue;
      entries.set(relPath.replace(/\.(ts|tsx)$/, ""), `./${relPath}`);
    } else if (entry.isDirectory) {
      const indexFile = await findIndexFile(fullPath);
      if (indexFile) {
        const indexName = indexFile.split("/").pop()!;
        entries.set(relPath, `./${relPath}/${indexName}`);
      } else {
        await scanDirectory(fullPath, relPath, entries);
      }
    }
  }
}

async function generateManifest(): Promise<void> {
  const entries = new Map<string, string>();

  // Root-level files only (flat modules like dashboard.tsx, index.ts)
  for await (const entry of Deno.readDir(modulesDir)) {
    const name = entry.name;
    if (skipEntry(name)) continue;
    if (!entry.isFile) continue;
    if (!name.endsWith(".ts") && !name.endsWith(".tsx")) continue;
    entries.set(name.replace(/\.(ts|tsx)$/, ""), `./${name}`);
  }

  // Category directories (directories without an index — recurse)
  for await (const entry of Deno.readDir(modulesDir)) {
    const name = entry.name;
    if (skipEntry(name)) continue;
    if (!entry.isDirectory) continue;
    const fullPath = join(modulesDir, name);
    const indexFile = await findIndexFile(fullPath);
    if (indexFile) {
      const indexName = indexFile.split("/").pop()!;
      entries.set(name, `./${name}/${indexName}`);
    } else {
      await scanDirectory(fullPath, name, entries);
    }
  }

  const lines: string[] = [];
  lines.push(
    "// Auto-generated by tools/generate-manifest.ts — do not edit manually",
  );
  lines.push(
    "//",
  );
  lines.push(
    "// Module Categorization",
  );
  lines.push(
    "//",
  );
  lines.push(
    "// Directories are either modules or categories:",
  );
  lines.push(
    "//   - A directory with an index.ts/index.tsx is a module (e.g., auth/surreal/)",
  );
  lines.push(
    "//   - A directory without an index is a category (e.g., auth/, demo/) —",
  ),
    lines.push(
      "//     its .ts/.tsx files and subdirectories with index.ts are scanned recursively",
    );
  lines.push(
    "//",
  );
  lines.push(
    "// Dot-prefixed entries at any depth are skipped (.form-auth-kv disables the KV backend)",
  );
  lines.push(
    "// Manifest keys are path segments joined with underscore (auth/password-change -> auth_password_change)",
  );
  lines.push("");

  const seen = new Set<string>();
  for (const [label, importPath] of entries) {
    let ident = toIdentifier(label);
    while (seen.has(ident)) {
      ident = `_${ident}`;
    }
    seen.add(ident);
    lines.push(`export { default as ${ident} } from "${importPath}";`);
  }

  if (lines.length > 2) lines.push("");

  await Deno.writeTextFile(manifestPath, lines.join("\n"));
  console.error(
    `Generated manifest with ${entries.size} module(s): ${
      [...entries.keys()].join(", ")
    }`,
  );
}

if (import.meta.main) {
  await generateManifest();
}
